[package]
name = "rassforge"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.2.7"
rand = "0.8.5"
md-5 = "0.10.5"
sha2 = "0.10.6"
sha1 = "0.10.5"
base32 = "0.4.0"
base64 = "0.21.0"